#!/usr/bin/env node
/**
 * Custom Framer SPA server
 * Generated by framer-export
 *
 * Usage: node server.js [port]
 * Default port: 8080
 */

const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.argv[2] || 8080;

// Kill any existing process on this port
const { execSync } = require('child_process');
try {
  if (process.platform === 'win32') {
    execSync(`for /f "tokens=5" %a in ('netstat -ano ^| findstr :${PORT}') do taskkill /F /PID %a`, { stdio: 'ignore' });
  } else {
    execSync(`lsof -ti:${PORT} | xargs kill -9 2>/dev/null || true`, { stdio: 'ignore' });
  }
} catch(e) {}

// Route slug → HTML file mapping (auto-generated)
const ROUTES = {
  '/': 'index.html'
};

const MIME = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.css': 'text/css',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.json': 'application/json',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.pdf': 'application/pdf',
};

const server = http.createServer((req, res) => {
  let url = req.url.split('?')[0];
  if (url.endsWith('/')) url = url.slice(0, -1);

  // Static file lookup
  const staticFile = path.join(__dirname, url);
  if (fs.existsSync(staticFile) && fs.statSync(staticFile).isFile()) {
    const ext = path.extname(staticFile);
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'text/plain' });
    fs.createReadStream(staticFile).pipe(res);
    return;
  }

  // Directory index.html
  const indexFile = path.join(__dirname, url, 'index.html');
  if (fs.existsSync(indexFile)) {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    fs.createReadStream(indexFile).pipe(res);
    return;
  }

  // Known route → serve its HTML
  if (ROUTES[url]) {
    const htmlPath = path.join(__dirname, ROUTES[url]);
    if (fs.existsSync(htmlPath)) {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      fs.createReadStream(htmlPath).pipe(res);
      return;
    }
  }

  // Slug fallback — try stripping path segments to find .html file
  // e.g. /blogs/some-post → blogs/some-post.html
  let search = url.replace(/^\//, '').replace(/\//g, '/');
  while (search.includes('/')) {
    const candidate = path.join(__dirname, search + '.html');
    if (fs.existsSync(candidate)) {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      fs.createReadStream(candidate).pipe(res);
      return;
    }
    search = search.substring(search.indexOf('/') + 1);
  }

  // Fallback to index.html
  res.writeHead(200, { 'Content-Type': 'text/html' });
  fs.createReadStream(path.join(__dirname, 'index.html')).pipe(res);
});

server.listen(PORT, () => {
  console.log(`Framer SPA server running at http://localhost:${PORT}`);
  console.log('Press Ctrl+C to stop');
});
